# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InstallButton = QtWidgets.QPushButton(self.centralwidget)
        self.InstallButton.setGeometry(QtCore.QRect(10, 70, 341, 61))
        self.InstallButton.setObjectName("InstallButton")
        self.RemoveButton = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveButton.setGeometry(QtCore.QRect(10, 140, 341, 61))
        self.RemoveButton.setObjectName("RemoveButton")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(10, 280, 341, 61))
        self.SearchButton.setObjectName("SearchButton")
        self.ShowButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowButton.setGeometry(QtCore.QRect(10, 350, 341, 61))
        self.ShowButton.setObjectName("ShowButton")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(10, 210, 341, 61))
        self.UpdateButton.setObjectName("UpdateButton")
        self.Tittle = QtWidgets.QLabel(self.centralwidget)
        self.Tittle.setGeometry(QtCore.QRect(10, 10, 341, 51))
        self.Tittle.setAlignment(QtCore.Qt.AlignCenter)
        self.Tittle.setObjectName("Tittle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 24))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionForum = QtWidgets.QAction(MainWindow)
        self.actionForum.setObjectName("actionForum")
        self.menuHelp.addAction(self.actionForum)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Idur"))
        self.InstallButton.setText(_translate("MainWindow", "Install"))
        self.RemoveButton.setText(_translate("MainWindow", "Remove"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.ShowButton.setText(_translate("MainWindow", "Show Details"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.Tittle.setText(_translate("MainWindow", "Visual Idur"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionForum.setText(_translate("MainWindow", "Forum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
