# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(284, 93)
        self.TextInput = QtWidgets.QTextEdit(Dialog)
        self.TextInput.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.TextInput.setObjectName("TextInput")
        self.OkButton = QtWidgets.QPushButton(Dialog)
        self.OkButton.setGeometry(QtCore.QRect(30, 50, 101, 27))
        self.OkButton.setObjectName("OkButton")
        self.CloseButton = QtWidgets.QPushButton(Dialog)
        self.CloseButton.setGeometry(QtCore.QRect(150, 50, 101, 27))
        self.CloseButton.setObjectName("CloseButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Write Here!"))
        self.OkButton.setText(_translate("Dialog", "Ok"))
        self.CloseButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
