# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(284, 102)
        self.OkButton = QtWidgets.QPushButton(Dialog)
        self.OkButton.setGeometry(QtCore.QRect(90, 70, 101, 27))
        self.OkButton.setObjectName("OkButton")
        self.TittleMessage = QtWidgets.QLabel(Dialog)
        self.TittleMessage.setGeometry(QtCore.QRect(0, 10, 281, 21))
        self.TittleMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.TittleMessage.setObjectName("TittleMessage")
        self.TittleMessage_2 = QtWidgets.QLabel(Dialog)
        self.TittleMessage_2.setGeometry(QtCore.QRect(0, 40, 281, 21))
        self.TittleMessage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TittleMessage_2.setObjectName("TittleMessage_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Message"))
        self.OkButton.setText(_translate("Dialog", "Ok"))
        self.TittleMessage.setText(_translate("Dialog", "About"))
        self.TittleMessage_2.setText(_translate("Dialog", "Visual Idur and Idur are made by Can202"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
